substitutions:
  _IMAGE_TAG: 'latest'
  _SERVICE_NAME: 'duckodesigns'
  _REGION: 'us-central1'
  _CLOUD_SQL_CONNECTION_NAME: 'ducko-designs:us-central1:duckodesigns-db'
  # DATABASE_URL is stored in Secret Manager - set via:
  # echo -n "postgresql://user:pass@localhost/db?host=/cloudsql/..." | gcloud secrets create database-url --data-file=- --project=PROJECT_ID
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/database-url/versions/latest
      env: 'DATABASE_URL'

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${_IMAGE_TAG}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
      - '.'
    id: 'build-image'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${_IMAGE_TAG}'
    id: 'push-image-sha'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
    id: 'push-image-latest'

  # Run database migrations before deployment (production best practice)
  # Migrations run in Cloud Build with database connection from Secret Manager
  # For Cloud Build, we use TCP connection to public IP
  # For Cloud Run, we use Unix socket connection (configured in deployment step)
  - name: 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${_IMAGE_TAG}'
    entrypoint: 'npx'
    args: ['prisma', 'migrate', 'deploy']
    env:
      - 'DATABASE_URL=${_DATABASE_URL}'
    id: 'run-migrations'
    waitFor: ['push-image-latest']
    secretEnv: ['DATABASE_URL']
    # Cloud Build service account must have Cloud SQL Client role
    # Database URL in secret should use public IP for Cloud Build: postgresql://user:pass@PUBLIC_IP:5432/dbname

  # Deploy container image to Cloud Run (only if migrations succeed)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${_IMAGE_TAG}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--port'
      - '8080'
      - '--service-account'
      - '${_SERVICE_NAME}-sa@$PROJECT_ID.iam.gserviceaccount.com'
      - '--add-cloudsql-instances'
      - '${_CLOUD_SQL_CONNECTION_NAME}'
      - '--update-secrets'
      - 'DATABASE_URL=cloud-run-database-url:latest'
      - '--update-env-vars'
      - 'GCS_BUCKET_NAME=duckodesigns-order-images,GCS_PROJECT_ID=$PROJECT_ID,NEXTAUTH_URL=https://${_SERVICE_NAME}-204661965330.${_REGION}.run.app'
    id: 'deploy-cloud-run'
    waitFor: ['run-migrations']

  # Ensure public access is enabled
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'add-iam-policy-binding'
      - '${_SERVICE_NAME}'
      - '--region'
      - '${_REGION}'
      - '--member'
      - 'allUsers'
      - '--role'
      - 'roles/run.invoker'
    id: 'set-public-access'

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${_IMAGE_TAG}'
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

